# Use the official Ubuntu base image
FROM ubuntu:20.04

# Install required packages and dependencies
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    sudo \
    gnupg \
    lsb-release

# Install Docker
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce

# Install Hasura CLI
RUN curl -L https://graphql-engine-cdn.hasura.io/ddn/cli/v2/get.sh | bash

# Set up a non-root user (optional)
ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get install -y sudo \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to non-root user (optional)
USER $USERNAME

# Run Hasura CLI login command as non-root user
RUN ddn auth login --pat $CODESPACES_SECRET_HASURA_PAT

# Set the shell to bash
CMD ["bash"]